local livingmatter = {
    ["minecraft:leaves"]         = 0.5,
    ["minecraft:leaves2"]        = 0.5,
    ["minecraft:red_mushroom"]   = 0.4,
    ["minecraft:pumpkin"]        = 0.9,
    ["minecraft:vine"]           = 0.4,
    ["minecraft:waterlily"]      = 0.4,
    ["minecraft:cocoa"]          = 0.8,
    ["minecraft:apple"]          = 1.0,
    ["minecraft:wheat"]          = 1.1,
    ["minecraft:wheat_seeds"]    = 0.4,
    ["minecraft:potato"]         = 1.5,
    ["minecraft:carrot"]         = 1.5,
    ["minecraft:sapling"]        = 0.5,
    ["minecraft:pumpkin_seeds"]  = 0.4,
    ["minecraft:melon_seeds"]    = 0.4,
    ["minecraft:beef"]           = 1.5,
    ["minecraft:porkchop"]       = 1.5,
    ["minecraft:mutton"]         = 1.5,
    ["minecraft:chicken"]        = 1.5,
    ["minecraft:rabbit"]         = 1.2,
    ["minecraft:rabbit_foot"]    = 1.0,
    ["minecraft:rabbit_hide"]    = 0.5,
    ["minecraft:beetroot"]       = 0.8,
    ["minecraft:hay_block"]      = 1.5,
    ["minecraft:beetroot_seeds"] = 0.4,
    ["minecraft:chorus_fruit"]   = 1.5,
    ["minecraft:fish"]           = 1.5,
    ["minecraft:reeds"]          = 1.0,
    ["minecraft:melon_block"]    = 1.0,
    ["minecraft:cactus"]         = 0.4,
    ["minecraft:red_flower"]     = 0.3,
    ["minecraft:yellow_flower"]  = 0.3,
    ["minecraft:chorus_flower"]  = 1.1,
    ["minecraft:brown_mushroom"] = 0.4
}

return livingmatter
